//construccion del array de los productos
export const dataInventory = 
[
    {
        id: 1,
        sku: 'Licor 1',
        upc: 123456789,
        cantidadDisp: 0,
        costo:15,
        precio:29,
        proveedor:'fabrica',
        marca:'inti',
        descripcion: 'inti producto',
        peso: 30,
        fechaExp: '',
    },
    {
        id: 2,
        sku: 'Soda 2',
        upc: 123456789,
        cantidadDisp: 0,
        costo:15,
        precio:29,
        proveedor:'fabrica',
        marca:'inti',
        descripcion: 'producto para retornar',
        peso: 20,
        fechaExp: '', 
    },
    {
        id: 3,
        sku: 'Jugos 3',
        upc: 123456789,
        cantidadDisp: 49,
        costo:15,
        precio:29,
        proveedor:'fabrica',
        marca:'inti',
        descripcion: 'producto daniado',
        peso: 10,
        fechaExp: '', 
    },
    {
        id: 4,
        sku: 'Extracto Frutas',
        upc: 123456789,
        cantidadDisp: 49,
        costo:15,
        precio:29,
        proveedor:'fabrica',
        marca:'inti',
        descripcion: 'producto sobre precio',
        peso: 50,
        fechaExp: '', 
    },
    {
        id: 5,
        sku: 'Agua',
        upc: 123456789,
        cantidadDisp: 49,
        costo:15,
        precio:29,
        proveedor:'fabrica',
        marca:'inti',
        descripcion: 'producto por pagar',
        peso: 70,
        fechaExp: '', 
    },
    {
        id: 6,
        sku: 'Acido',
        upc: 123456789,
        cantidadDisp: 49,
        costo:15,
        precio:29,
        proveedor:'fabrica',
        marca:'inti',
        descripcion: 'producto por pagar',
        peso: 10,
        fechaExp: '', 
    },
    {
        id: 7,
        sku: 'Veneno',
        upc: 123456789,
        cantidadDisp: 49,
        costo:15,
        precio:29,
        proveedor:'fabrica',
        marca:'inti',
        descripcion: 'producto por pagar',
        peso: 24,
        fechaExp: '', 
    },
    {
        id: 8,
        sku: 'Meta',
        upc: 123456789,
        cantidadDisp: 49,
        costo:15,
        precio:29,
        proveedor:'fabrica',
        marca:'inti',
        descripcion: 'producto por pagar a heinsenberg',
        peso: 240,
        fechaExp: '', 
    },
    {
        id: 9,
        sku: 'Ron',
        upc: 123456789,
        cantidadDisp: 49,
        costo:15,
        precio:29,
        proveedor:'fabrica',
        marca:'inti',
        descripcion: 'producto pagado',
        peso: 90,
        fechaExp: '', 
    },
    {
        id: 10,
        sku: 'Cerveza',
        upc: 123456789,
        cantidadDisp: 49,
        costo:15,
        precio:29,
        proveedor:'fabrica',
        marca:'inti',
        descripcion: 'producto agotado',
        peso: 40,
        fechaExp: '', 
    },
    {
        id: 11,
        sku: 'Tequila',
        upc: 123456789,
        cantidadDisp: 49,
        costo:15,
        precio:29,
        proveedor:'fabrica',
        marca:'inti',
        descripcion: 'producto por reponer',
        peso: 240,
        fechaExp: '', 
    },
    {
        id: 12,
        sku: 'Licores Varios',
        upc: 123456789,
        cantidadDisp: 49,
        costo:15,
        precio:29,
        proveedor:'fabrica',
        marca:'inti',
        descripcion: 'Mas vendido',
        peso: 228,
        fechaExp: '', 
    },
    {
        id: 13,
        sku: 'Cerveza Artesanal',
        upc: 123456789,
        cantidadDisp: 49,
        costo:15,
        precio:29,
        proveedor:'fabrica',
        marca:'inti',
        descripcion: 'Por Cobrar',
        peso: 228,
        fechaExp: '', 
    },
    {
        id: 14,
        sku: 'Vodka Ruso',
        upc: 123456789,
        cantidadDisp: 49,
        costo:15,
        precio:29,
        proveedor:'fabrica',
        marca:'inti',
        descripcion: 'Sobrevendido',
        peso: 228,
        fechaExp: '', 
    },
    {
        id: 15,
        sku: 'Ron Barato',
        upc: 123456789,
        cantidadDisp: 49,
        costo:15,
        precio:29,
        proveedor:'fabrica',
        marca:'inti',
        descripcion: 'No vendido',
        peso: 228,
        fechaExp: '', 
    },
    {
        id: 16,
        sku: 'Yupi con Alcohol',
        upc: 123456789,
        cantidadDisp: 49,
        costo:15,
        precio:29,
        proveedor:'fabrica',
        marca:'inti',
        descripcion: 'Inversion',
        peso: 228,
        fechaExp: '', 
    },
    {
        id: 17,
        sku: 'Pasta Base',
        upc: 123456789,
        cantidadDisp: 49,
        costo:15,
        precio:29,
        proveedor:'fabrica',
        marca:'inti',
        descripcion: 'inti Producto',
        peso: 228,
        fechaExp: '', 
    },
    {
        id: 18,
        sku: 'Cokaine',
        upc: 123456789,
        cantidadDisp: 49,
        costo:15,
        precio:29,
        proveedor:'fabrica',
        marca:'inti',
        descripcion: 'Descuento Proximos, para intis clientes y para intis subscriptores que tengan la tarjeta de descuento del negocio para',
        peso: 228,
        fechaExp: '', 
    },
    {
        id: 19,
        sku: 'Wuid',
        upc: 123456789,
        cantidadDisp: 49,
        costo:15,
        precio:29,
        proveedor:'fabrica',
        marca:'inti',
        descripcion: 'inti Mercado',
        peso: 228,
        fechaExp: '', 
    },
    {
        id: 20,
        sku: 'LDC Heavy Drug',
        upc: 123456789,
        cantidadDisp: 49,
        costo:15,
        precio:29,
        proveedor:'fabrica',
        marca:'inti',
        descripcion: 'Descuentos',
        peso: 228,
        fechaExp: '', 
    },
]
//las fechas van a llegar tipo string. calculo de fechas en el
const getTodayDate = (): string => {
    const today = new Date();
    const year = today.getFullYear();
    const month = String(today.getMonth() + 1).padStart(2, '0'); 
    const day = String(today.getDate()).padStart(2, '0'); 
  
    return `${day}-${month}-${year}`;
  };

const fillUpDate = () => {
    for(let i = 0; i<dataInventory.length; ++i){
        dataInventory[i].fechaExp = `${getTodayDate()}`;
    }
}

fillUpDate();