//construccion del array de los productos

export const dataInventory = 
[
    {
        id: 1,
        sku: 'Licor 1',
        upc: 123456789,
        cantidadDisp: 0,
        costo:15,
        precio:29,
        proveedor:'fabrica',
        etiquetas:'nuevo',
        descripcion: 'nuevo producto',
        peso: 30,
        fechaExp:'30-11-2024'
    },
    {
        id: 2,
        sku: 'Soda 2',
        upc: 123456789,
        cantidadDisp: 0,
        costo:15,
        precio:29,
        proveedor:'fabrica',
        etiquetas:'nuevo',
        descripcion: 'producto para retornar',
        peso: 20,
        fechaExp:'30-11-2024'
    },
    {
        id: 3,
        sku: 'Jugos 3',
        upc: 123456789,
        cantidadDisp: 49,
        costo:15,
        precio:29,
        proveedor:'fabrica',
        etiquetas:'nuevo',
        descripcion: 'producto daniado',
        peso: 10,
        fechaExp:'30-11-2024'
    },
    {
        id: 4,
        sku: 'Extracto Frutas',
        upc: 123456789,
        cantidadDisp: 49,
        costo:15,
        precio:29,
        proveedor:'fabrica',
        etiquetas:'nuevo',
        descripcion: 'producto sobre precio',
        peso: 50,
        fechaExp:'30-11-2024'
    },
    {
        id: 5,
        sku: 'Agua',
        upc: 123456789,
        cantidadDisp: 49,
        costo:15,
        precio:29,
        proveedor:'fabrica',
        etiquetas:'nuevo',
        descripcion: 'producto por pagar',
        peso: 70,
        fechaExp:'30-11-2024'
    },
    {
        id: 6,
        sku: 'Acido',
        upc: 123456789,
        cantidadDisp: 49,
        costo:15,
        precio:29,
        proveedor:'fabrica',
        etiquetas:'nuevo',
        descripcion: 'producto por pagar',
        peso: 10,
        fechaExp:'30-11-2024'
    },
    {
        id: 7,
        sku: 'Veneno',
        upc: 123456789,
        cantidadDisp: 49,
        costo:15,
        precio:29,
        proveedor:'fabrica',
        etiquetas:'nuevo',
        descripcion: 'producto por pagar',
        peso: 24,
        fechaExp:'30-11-2024'
    },
    {
        id: 8,
        sku: 'Meta',
        upc: 123456789,
        cantidadDisp: 49,
        costo:15,
        precio:29,
        proveedor:'fabrica',
        etiquetas:'nuevo',
        descripcion: 'producto por pagar a heinsenberg',
        peso: 240,
        fechaExp:'30-11-2024'
    },
    {
        id: 9,
        sku: 'Ron',
        upc: 123456789,
        cantidadDisp: 49,
        costo:15,
        precio:29,
        proveedor:'fabrica',
        etiquetas:'nuevo',
        descripcion: 'producto pagado',
        peso: 90,
        fechaExp:'30-11-2024'
    },
    {
        id: 10,
        sku: 'Cerveza',
        upc: 123456789,
        cantidadDisp: 49,
        costo:15,
        precio:29,
        proveedor:'fabrica',
        etiquetas:'nuevo',
        descripcion: 'producto agotado',
        peso: 40,
        fechaExp:'30-11-2024'
    },
    {
        id: 11,
        sku: 'Tequila',
        upc: 123456789,
        cantidadDisp: 49,
        costo:15,
        precio:29,
        proveedor:'fabrica',
        etiquetas:'nuevo',
        descripcion: 'producto por reponer',
        peso: 240,
        fechaExp:'30-11-2024'
    },
    {
        id: 12,
        sku: 'Licores Varios',
        upc: 123456789,
        cantidadDisp: 49,
        costo:15,
        precio:29,
        proveedor:'fabrica',
        etiquetas:'nuevo',
        descripcion: 'Mas vendido',
        peso: 228,
        fechaExp:'30-11-2024'
    },
    {
        id: 13,
        sku: 'Cerveza Artesanal',
        upc: 123456789,
        cantidadDisp: 49,
        costo:15,
        precio:29,
        proveedor:'fabrica',
        etiquetas:'nuevo',
        descripcion: 'Por Cobrar',
        peso: 228,
        fechaExp:'30-11-2024'
    },
    {
        id: 14,
        sku: 'Vodka Ruso',
        upc: 123456789,
        cantidadDisp: 49,
        costo:15,
        precio:29,
        proveedor:'fabrica',
        etiquetas:'nuevo',
        descripcion: 'Sobrevendido',
        peso: 228,
        fechaExp:'30-11-2024'
    },
    {
        id: 15,
        sku: 'Ron Barato',
        upc: 123456789,
        cantidadDisp: 49,
        costo:15,
        precio:29,
        proveedor:'fabrica',
        etiquetas:'nuevo',
        descripcion: 'No vendido',
        peso: 228,
        fechaExp:'30-11-2024'
    },
    {
        id: 16,
        sku: 'Yupi con Alcohol',
        upc: 123456789,
        cantidadDisp: 49,
        costo:15,
        precio:29,
        proveedor:'fabrica',
        etiquetas:'nuevo',
        descripcion: 'Inversion',
        peso: 228,
        fechaExp:'30-11-2024'
    },
    {
        id: 17,
        sku: 'Pasta Base',
        upc: 123456789,
        cantidadDisp: 49,
        costo:15,
        precio:29,
        proveedor:'fabrica',
        etiquetas:'nuevo',
        descripcion: 'Nuevo Producto',
        peso: 228,
        fechaExp:'30-11-2021'
    },
    {
        id: 18,
        sku: 'Cokaine',
        upc: 123456789,
        cantidadDisp: 49,
        costo:15,
        precio:29,
        proveedor:'fabrica',
        etiquetas:'nuevo',
        descripcion: 'Descuento Proximos, para nuevos clientes y para nuevos subscriptores que tengan la tarjeta de descuento del negocio para',
        peso: 228,
        fechaExp:'30-11-2022'
    },
    {
        id: 19,
        sku: 'Wuid',
        upc: 123456789,
        cantidadDisp: 49,
        costo:15,
        precio:29,
        proveedor:'fabrica',
        etiquetas:'nuevo',
        descripcion: 'Nuevo Mercado',
        peso: 228,
        fechaExp:'30-01-2023'
    },
    {
        id: 20,
        sku: 'LDC Heavy Drug',
        upc: 123456789,
        cantidadDisp: 49,
        costo:15,
        precio:29,
        proveedor:'fabrica',
        etiquetas:'nuevo',
        descripcion: 'Descuentos',
        peso: 228,
        fechaExp:'30-05-2024'
    },
]